local gitsigns = require('gitsigns')
local gitsigns_actions = require('gitsigns.actions')
local vimp = require('vimp')

vimp.nnoremap('<leader>hr', gitsigns.reset_hunk)
vimp.vnoremap('<leader>hr', function()
	gitsigns.reset_hunk({ vim.fn.line('.'), vim.fn.line('v') })
end)
vimp.nnoremap('<leader>hR', gitsigns.reset_buffer)
vimp.nnoremap('<leader>hp', gitsigns.preview_hunk)
vimp.nnoremap('<leader>h[', gitsigns_actions.prev_hunk)
vimp.nnoremap('<leader>h]', gitsigns_actions.next_hunk)
vimp.nnoremap('<leader>hb', function()
	gitsigns.blame_line({ full = true })
end)
