vimp.nnoremap({ 'silent' }, '<F9>', ':FloatermPrev<CR>')
vimp.tnoremap({ 'silent' }, '<F9>', [[<C-\><C-n>:FloatermPrev<CR>]])
vimp.nnoremap({ 'silent' }, '<F10>', ':FloatermNext<CR>')
vimp.tnoremap({ 'silent' }, '<F10>', [[<C-\><C-n>:FloatermNext<CR>]])
vimp.nnoremap({ 'silent' }, '<F11>', ':FloatermNew<CR>')
vimp.tnoremap({ 'silent' }, '<F11>', [[<C-\><C-n>:FloatermNew<CR>]])
vimp.nnoremap({ 'silent' }, '<F12>', ':FloatermToggle<CR>')
vimp.tnoremap({ 'silent' }, '<F12>', [[<C-\><C-n>:FloatermToggle<CR>]])
